# Generated by Django 4.2.7 on 2023-11-21 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0003_remove_rents_rent_id_rents_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rents",
            name="id",
        ),
        migrations.AddField(
            model_name="rents",
            name="bedrooms",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rents",
            name="bethrooms",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rents",
            name="comments",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.comments",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rents",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rents",
            name="location",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rents",
            name="price",
            field=models.DecimalField(decimal_places=10, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rents",
            name="published_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rents",
            name="rent_id",
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rents",
            name="reviews_avg",
            field=models.DecimalField(decimal_places=5, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rents",
            name="reviews_nb",
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rents",
            name="status",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rents",
            name="title",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rents",
            name="user_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="home.user"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
