# Generated by Django 4.2.7 on 2023-12-04 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_user_dni_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rents",
            name="comments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.comments",
            ),
        ),
        migrations.AlterField(
            model_name="rents",
            name="reviews_avg",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rents",
            name="reviews_nb",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
    ]
