# Generated by Django 4.2.7 on 2023-12-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_rents_comments_alter_rents_reviews_avg_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="rents",
            new_name="Post",
        ),
    ]
